---
# Used to accept all hostkeys of all machines
- hosts: all
  gather_facts: no
  tasks:
  - name: run ssh-keyscan to add keys to known_hosts for vagrant
    local_action: shell ssh-keyscan {{ inventory_hostname }} >> /home/vagrant/.ssh/known_hosts    